{% set name = "a2wsgi" %}
{% set version = "1.10.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/a2wsgi-{{ version }}.tar.gz
  sha256: 7ca30b71c69b688c3a19b911be5bc78506e1b7507768951ed7ed010e7b2164af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - a2wsgi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/abersheeran/a2wsgi
  summary: Convert WSGI app to ASGI app or ASGI app to WSGI app.
  dev_url: https://github.com/abersheeran/a2wsgi
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
